version: '3.8'
 
services:
  webserver:
    image: u5569451/csvs_webserver_i
    container_name: u5569451_csvs_webserver_c
    networks:
      u5569451_csvs_dbserver_net:
        ipv4_address: 203.0.113.200
    build:
      context: ./webserver
    security_opt:
      - no-new-privileges:true
      - seccomp:./webserver/webserver_seccomp.json
    ports:
      - "8080:80"
      - "8004:8004"
      #- "2375:2375"
      - "2222:22"
    deploy:
      mode: global  # changed to global but by default mode is replicated
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/"]
      interval: 2m30s
      timeout: 10s
      retries: 2
      start_period: 2m
    cap_drop:
      - SYS_PTRACE
      - SYS_RAWIO
      - NET_RAW
      - SYS_MODULE
    depends_on:
      - db.cyber23.test

  db.cyber23.test:
    image: u5569451/csvs_dbserver_i
    container_name: u5569451_csvs_dbserver_c
    networks:
      u5569451_csvs_dbserver_net:
        ipv4_address: 203.0.113.201
    hostname: db.cyber23.test
    build:
      context: ./dbserver
    environment:
      MARIADB_ROOT_PASSWORD: CorrectHorseBatteryStaple  # Set database root password
      MARIADB_DATABASE: csvs23db                     # Set database name
      MARIADB_USER: wwwclient23                      # Set non-root user
      MARIADB_PASSWORD: wwwclient23Creds             # Set non-root user's password
    security_opt:
      - no-new-privileges:true
      - seccomp:./dbserver/dbserver_seccomp.json
      #- apparmor:./dbserver/dbserver_apparmor.d
    ports:
      - "3307:3306"
    deploy:
      mode: global  # changed to global but by default mode is replicated
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 20M
      restart_policy:
        condition: on-failure
    volumes:
      - ./dbserver/sqlconfig/csvs23db.sql:/docker-entrypoint-initdb.d/csvs23db.sql
      - mariadb_data:/var/lib/mysql  # Adding a volume for data persistence in mariadb data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/"]
      interval: 2m30s
      timeout: 10s
      retries: 2
      start_period: 2m
    cap_drop:
      - SYS_PTRACE
      - NET_RAW
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - AUDIT_WRITE

volumes:
  mariadb_data:
networks:
  u5569451_csvs_dbserver_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.0/24
